# Welcome to Jekyll!
#

# Site settings
title: Doepware
description: Your source for wildly stylish and unique repurposed clothing and handmade designs
owner: Doepware # or company name
first_published: 2018 # if migrating another site, the year of your first publish
email: zman0006@hotmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://zazalak.github.io" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/<username>
  #github: https://github.com/<username>
  #linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/doepware
  #google-plus-square: https://plus.google.com/u/0/+<username>
  email: zman0006@gmail.com
  #flickr:
  instagram: doepware
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
